version: 1.3.{build}
image: Visual Studio 2017
before_build:
  - nuget restore
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.3.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a asmspy.%APPVEYOR_BUILD_VERSION%.zip .\AsmSpy.CommandLine\bin\Debug\AsmSpy.exe

    appveyor PushArtifact asmspy.%APPVEYOR_BUILD_VERSION%.zip -DeploymentName ReleaseZip
    
    choco pack .\AsmSpy.CommandLine\AsmSpy.nuspec --version %APPVEYOR_BUILD_VERSION%

    appveyor PushArtifact asmspy.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName ReleaseNuGet
    
    nuget pack .\AsmSpy.Core\AsmSpy.Core.nuspec -version %APPVEYOR_BUILD_VERSION%

    appveyor PushArtifact AsmSpy.Core.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName AsmSpy.Core
deploy:
- provider: Environment
  name: AsmSpy Chocolatey
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: Environment
  name: AsmSpy Nuget
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
